# Generated by Django 3.0.7 on 2021-03-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinayaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Mobile_number',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='details',
            name='Pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
