# Generated by Django 3.1.6 on 2021-03-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinayaga', '0002_auto_20210307_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=40)),
                ('Company_address', models.CharField(max_length=100)),
                ('Landmark', models.CharField(max_length=40)),
                ('District', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Pincode', models.IntegerField()),
                ('Mobile_number', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('Machine_name', models.CharField(max_length=30)),
                ('Machine_condition', models.TextField(max_length=1000)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
