# Generated by Django 3.1.6 on 2021-03-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinayaga', '0003_auto_20210309_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
