# Generated by Django 3.1.6 on 2021-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinayaga', '0005_auto_20210322_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='Image5',
        ),
        migrations.AddField(
            model_name='detail',
            name='Image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
