# Generated by Django 3.1.6 on 2021-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinayaga', '0006_auto_20210402_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=40)),
                ('Person_name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=1000)),
                ('Mobile_number', models.IntegerField()),
            ],
        ),
    ]
