# Generated by Django 3.1.6 on 2021-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinayaga', '0008_auto_20210423_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Company_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Company_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Landmark',
            field=models.CharField(max_length=40),
        ),
    ]
