# Generated by Django 3.1.6 on 2021-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinayaga', '0009_auto_20210513_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='District',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='detail',
            name='State',
            field=models.CharField(max_length=15),
        ),
    ]
